/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
/**
 *
 * @author HP
 */
public class PilihGambarButtonComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagepanel = new javax.swing.JPanel();
        glassfishLB = new javax.swing.JLabel();
        javaeeLB = new javax.swing.JLabel();
        postgresqlLB = new javax.swing.JLabel();
        buttonlayout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihpilihanCard = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagepanel.setLayout(new java.awt.CardLayout());

        glassfishLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glassfishLB.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Pemrograman Berbasis Objek 2\\Tugas\\Glassfish.jpg")); // NOI18N
        imagepanel.add(glassfishLB, "0");

        javaeeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaeeLB.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Pemrograman Berbasis Objek 2\\Tugas\\JavaEE.jpg")); // NOI18N
        imagepanel.add(javaeeLB, "1");

        postgresqlLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postgresqlLB.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 5\\Pemrograman Berbasis Objek 2\\Tugas\\PostgreSQL.jpg")); // NOI18N
        imagepanel.add(postgresqlLB, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Pilih Gambar");
        buttonlayout.add(jLabel1);

        pilihpilihanCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glasfish", "JavaEE", "PostgreSQL" }));
        pilihpilihanCard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihpilihanCardItemStateChanged(evt);
            }
        });
        pilihpilihanCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihpilihanCardActionPerformed(evt);
            }
        });
        buttonlayout.add(pilihpilihanCard);

        getContentPane().add(buttonlayout, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihpilihanCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihpilihanCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihpilihanCardActionPerformed

    private void pilihpilihanCardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihpilihanCardItemStateChanged
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, String.valueOf(pilihpilihanCard.getSelectedIndex()));
    }//GEN-LAST:event_pilihpilihanCardItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButtonComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonlayout;
    private javax.swing.JLabel glassfishLB;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel javaeeLB;
    private javax.swing.JComboBox<String> pilihpilihanCard;
    private javax.swing.JLabel postgresqlLB;
    // End of variables declaration//GEN-END:variables
}
